# Site settings
author: Rebecca Hunt
title: Eating Mud
header-img: img/home-bg.png
email: rebeccahunt034@gmail.com
copyright_name: Rebecca Hunt
description: > # this means to ignore newlines until "baseurl:"
  Software Engineer, Computers and humans
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  RebeccaHA

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
